### PR TITLE
Team 2021 Object

### PR DESCRIPTION
**Pull request by ShivangM**
Converted Team2021 to Object and removed some unrequited files.

### CODE REVIEW

**Comment by ShivangM** [comment]
Changed Front Banner Theme

**Comment by SanjaySinghRajpoot** [comment]
kindly share the screenshots of the changes made.

**Comment by ShivangM** [comment]
image
image

**Comment by SanjaySinghRajpoot** [comment]
ok thanks

**Review by SanjaySinghRajpoot — APPROVED** [review]

**Pull request merged**
